name: laravel-schedule-telegram-output
project_type: laravel
docroot: ''
php_version: '8.2'
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: false
composer_version: '2'
web_environment: []
omit_containers: [db]
disable_settings_management: true 